exercises/urls.py
from django.urls import path

from exercises import views

app_name = "exercises"


urlpatterns = [
    path("", views.index, name="index"),
    path("routines", views.RoutineList.as_view(), name="routines_list"),
    path("create", views.CreateWorkout.as_view(), name="create_workout"),
    path("active", views.UpdateWorkout.as_view(), name="active_workout"),
    path("history", views.WorkoutHistory.as_view(), name="history"),
    path(
        "<slug:exercise_id>/sets/create", views.CreateSet.as_view(), name="create_set"
    ),
    path("routines/create", views.CreateRoutine.as_view(), name="create_routine"),
]

workout/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from exercises.views import Register, redirect_to_login

urlpatterns = [
    path("", redirect_to_login, name="login_redirect"),
    path("accounts/register/", Register.as_view(), name="register"),
    path("accounts/login/", LoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("exercises/", include("exercises.urls")),
]

exercises/models.py
from django.contrib.auth.models import User
from django.db import models


class Routine(models.Model):
    """A collection of exercises."""

    def __str__(self):
        """List as the name."""
        return self.name

    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="routines")


class AbstractExercise(models.Model):
    """An exercise for a routine."""

    name = models.CharField(max_length=200)
    routine = models.ForeignKey(
        Routine, on_delete=models.CASCADE, related_name="exercises"
    )


class Workout(models.Model):
    """An instance of working out to a routine."""

    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="workouts")


class Set(models.Model):
    """A runthrough of an exercise."""

    weight = models.IntegerField(default=0)
    reps = models.IntegerField(default=0)


class Exercise(models.Model):
    """A particular exercise in a routine."""

    name = models.CharField(max_length=200)
    workout = models.ForeignKey(
        Workout, on_delete=models.CASCADE, related_name="exercises"
    )
    sets = models.ManyToManyField(Set, related_name="sets")

    @property
    def set_summary(self):
        """Summary of the sets."""
        return ", ".join(f"{set.weight}lbs, {set.reps}x" for set in self.sets.all())

exercises/forms.py
from django import forms


class CreateWorkoutForm(forms.Form):
    """Form for creating a workout from a routine."""

    routine = forms.ChoiceField()


class UpdateWorkoutForm(forms.Form):
    """Form for updating the progress of a workout."""

    is_completed = forms.BooleanField()


class CreateSetForm(forms.Form):
    """Create a set for an exercise."""

    weight = forms.IntegerField()
    reps = forms.IntegerField()
    exercise_id = forms.IntegerField()


class CreateRoutineForm(forms.Form):
    """Create a routine."""

    name = forms.CharField(max_length=200)
    exercises = forms.CharField(
        max_length=500, help_text="Comma separated list of exercises"
    )

exercises/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import QuerySet
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView

from exercises.forms import CreateRoutineForm, CreateWorkoutForm, UpdateWorkoutForm
from exercises.models import AbstractExercise, Exercise, Routine, Set, Workout


class Register(FormView):
    """Sign up!"""

    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy("exercises:index")
    template_name = "register.html"

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


def redirect_to_login(request):
    """Redirect to the index or login page."""
    return redirect(reverse("exercises:index"))


@login_required
def index(request):
    """Just display a page."""
    return render(request, "exercises/index.html")


class RoutineList(LoginRequiredMixin, ListView):
    """Displays a user's routines in a table."""

    model = Routine

    def get_queryset(self) -> QuerySet[Routine]:
        """Defines the user's routines queryset."""
        return Routine.objects.filter(owner=self.request.user)


class CreateRoutine(LoginRequiredMixin, FormView):
    """Create a new routine."""

    form_class = CreateRoutineForm
    template_name = "exercises/create_routine_form.html"
    success_url = reverse_lazy("exercises:create_workout")

    def form_valid(self, form):
        """Verify we have exercises."""
        if form.is_valid():
            routine = Routine.objects.create(
                name=form.cleaned_data["name"],
                owner=self.request.user,
            )
            exercises = [
                exercise.strip()
                for exercise in form.cleaned_data["exercises"].split(",")
            ]
            for exercise in exercises:
                AbstractExercise.objects.create(name=exercise, routine=routine)
            return super().form_valid(form)
        return render(
            self.request,
            reverse("exercises:create_set"),
            {"form": form},
        )


class CreateWorkout(LoginRequiredMixin, FormView):
    """Start a new workout for a given routine."""

    form_class = CreateWorkoutForm
    template_name = "exercises/workout_form.html"
    success_url = reverse_lazy("exercises:active_workout")

    def get_form(self, *args, **kwargs):
        routines = self.request.user.routines.all()
        form = super().get_form(*args, **kwargs)
        form.fields["routine"].choices = [("", "--------")] + list(
            (routine.name, routine.name) for routine in routines
        )
        return form

    def form_valid(self, form):
        """Verify we have a routine to make the workout out of."""
        if form.is_valid():
            Workout.objects.filter(owner=self.request.user, is_completed=False).update(
                is_completed=True, completed_at=timezone.now()
            )
            workout = Workout.objects.create(owner=self.request.user)
            routine = Routine.objects.filter(
                name=form.cleaned_data["routine"],
                owner=self.request.user,
            ).first()
            for abstract_exercise in routine.exercises.all():
                Exercise.objects.create(name=abstract_exercise.name, workout=workout)
            return redirect(reverse("exercises:active_workout"))
        return render(
            self.request,
            reverse("exercises:create_workout"),
            {"form": form},
        )


class UpdateWorkout(LoginRequiredMixin, FormView):
    """Update the workout with the sets done."""

    form_class = UpdateWorkoutForm
    template_name = "exercises/active_workout.html"
    success_url = reverse_lazy("exercises:history")

    def get_context_data(self, **kwargs):
        """Prep data for the form."""
        data = super().get_context_data(**kwargs)
        data["exercises"] = []
        workout = Workout.objects.filter(
            owner=self.request.user, is_completed=False
        ).first()
        for exercise in workout.exercises.all():
            data["exercises"].append(exercise)
        return data

    def form_valid(self, form):
        """Update!"""
        if form.is_valid():
            workout = Workout.objects.filter(
                owner=self.request.user, is_completed=False
            ).first()
            workout.completed_at = timezone.now()
            workout.is_completed = True
            workout.save()
            return super().form_valid(form)

        return render(
            self.request,
            reverse("exercises:active_workout"),
            {"form": form},
        )

    def form_invalid(self, form):
        return super().form_invalid(form)


class CreateSet(LoginRequiredMixin, CreateView):
    """Start a new set for a given exercise."""

    model = Set
    fields = ["weight", "reps"]
    success_url = reverse_lazy("exercises:active_workout")

    def form_valid(self, form):
        """Verify we have a routine to make the workout out of."""
        if form.is_valid():
            Exercise.objects.get(pk=int(self.kwargs["exercise_id"])).sets.add(
                Set.objects.create(
                    weight=form.cleaned_data["weight"],
                    reps=form.cleaned_data["reps"],
                )
            )
            return redirect(reverse("exercises:active_workout"))
        return render(
            self.request,
            reverse("exercises:create_set"),
            {"form": form},
        )


class WorkoutHistory(LoginRequiredMixin, ListView):
    """List completed workouts."""

    model = Workout
    template_name = "exercises/workout_history.html"

    def get_queryset(self) -> QuerySet[Workout]:
        """Defines the user's routines queryset."""
        return Workout.objects.filter(
            owner=self.request.user,
            is_completed=True,
        ).order_by("-completed_at")

exercises/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, width=device-width">

    <!-- http://getbootstrap.com/docs/4.5/ for CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- http://getbootstrap.com/docs/4.5/ for JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- https://favicon.io/emoji-favicons/flexed-biceps -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link href="{% static 'styles.css' %}" rel="stylesheet">


    <title>Work It: {% block title %}{% endblock %}</title>

    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';
        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');
          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
      </script>

  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light border">
      <a class="navbar-brand" href="/"><img src="{% static 'favicon.ico' %}" /><span class="brand-text">Exercise Tracker</span></a>
      <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbar" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        {% if user.is_authenticated %}
            <ul class="navbar-nav mt-2">
                <li class="nav-item"><a class="nav-link" href="{% url 'exercises:routines_list' %}">Routines</a></li>
            </ul>
            <ul class="navbar-nav mr-auto mt-2">
              <li class="nav-item"><a class="nav-link" href="{% url 'exercises:history' %}">History</a></li>
          </ul>

            <ul class="navbar-nav ml-auto mt-2">
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Log Out</a></li>
            </ul>
        {% else %}
            <ul class="navbar-nav ml-auto mt-2">
                <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Register</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Log In</a></li>
            </ul>
        {% endif %}
      </div>
    </nav>

    <main class="container py-5 text-center">
        {% block main %}{% endblock %}
    </main>

    <footer class="footer small text-center text-muted">
        Copyright Christopher Walsh 2021.
    </footer>
  </body>
</html>

exercises/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block main %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Signup">
</form>

Already registered? Log in <a href="{% url 'login' %}">here</a>.
{% endblock %}